### ISSUE TITLE
test gpkitmodels via Jenkins

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gplibrary#111]
Set up testing infrastructure and get baseline set up tests passing. Will encourage testing of models in this repo.

**Comment by galbramc** [comment]
Let me know when there is a script that can be executed by jenkins.

**Comment by mjburton11** [comment]
@galbramc @bqpd can we finish this?

**Comment by galbramc** [comment]
Someone needs to be put in charge of setting up the infrastructure to write and run tests. Once that is in place we can have jenkins run the tests.

**Comment by mjburton11** [comment]
To start, can we have it run gas_solar_trade and jho tests?

**Comment by bqpd** [comment]
@galbramc, we're thinking we'll want the following functionality first:

On a push to this repo, run the gpkit models tests
On a PR to this repo, we'll want to use the gpkit models with the modification that it should use that particular branch of GPkit models; I imagine this'll be a small modification to your `jenkins_test.py` script?

(the step after this will be adding a TESTS file to this repo like all the other research repos)

**Comment by bqpd** [comment]
I think https://acdl.mit.edu/csi/view/convexengineering/job/gpkit_commons_Push_Models/ implements what we need, but I'm not sure how to get it to trigger on pushes

**Comment by galbramc** [comment]
I don't think the acdl-jenkins user has permissions to create webhooks. It needs complete admin privileges.

**Comment by bqpd** [comment]
it is now an admin!

**Comment by galbramc** [comment]
hmm, still says it only has push/pull permissions... does it take a moment to take affect?

**Comment by bqpd** [comment]
shouldn't!

**Comment by bqpd** [comment]
ah, my mistake. try now.

**Comment by galbramc** [comment]
yep that seems to have worked now

**Comment by galbramc** [comment]
Something is funny with the script. I tried cloning gpkit and we get this error on reynolds:

git clone --depth 1 git@github.com:convexengineering/gpkit.git
Cloning into 'gpkit'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by bqpd** [comment]
Oh, it should probably use http then...will modify

**Comment by bqpd** [comment]
This is now done!
