### ISSUE TITLE
proposal to rename this repository

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gplibrary#117]
- models
  - library
  - buildingblocks
  - resources
  - commons
  - common

which of those do you like best?

**Comment by bqpd** [comment]
Consensus in the corner office is `commons`

**Comment by 1ozturkbe** [comment]
Hmm when it comes to this, I prefer a conventional 'library', or 'models'. 'commons' is a little weird, especially it is not really a commons. It is more like a select list of vetted models, and thus a 'library'. But I don't feel very strongly about the name.

**Comment by 1ozturkbe** [comment]
@bqpd hmm this repo is called gplibrary and has SPs in it? Perhaps at the minimum we should make the README say that it has both.

**Comment by bqpd** [comment]
What about celibrary?

**Comment by 1ozturkbe** [comment]
well why put ce when the directory is convexengineering/library?

**Comment by bqpd** [comment]
Talking in person we in the end favoured gplibrary
