### ISSUE TITLE
Different versions of SimPleAC

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gplibrary#130]
I'm improving up SimPleAC in many aspects as part of my thesis as a demo of extensibility and modularity of GP models. For the thesis itself, I am hoping to submit code that has been incrementally modified (SimPleAC, SimPleAC with engine, SimPleAC with submodels, SimPleAC with performance modeling etc.).  I was wondering if you had preferences as to how the code is integrated into GPlibrary (eg. two extremes: only submit final version, vs. submit versions for every incremental improvement). Let me know if you have ideas.

**Comment by bqpd** [comment]
I would include the named different versions in a folder! If you want to reduce code duplication, each can import the previous with `from FOO import *`

**Comment by 1ozturkbe** [comment]
This will be resolved with PR #172
