### ISSUE TITLE
importing models / repo name

### ISSUE THREAD

**Issue by whoburg** [convexengineering/gplibrary#50]
The current repo name, `gpkit-models` is not a valid python package name. Is this an issue? How does one import a model or for that matter, install gpkit-models?
- [ ] do we need an install script?
- [ ] should we move all models into a `models` dir that is a python package with an `__init__`, or
- [ ] should we rename the repo?

**Comment by bqpd** [comment]
* I think we'll want an install script if we use markdown files.
  * I do think the name should be `gpmodels` or `gpkitmodels` or `gpkit_models`.
