### ISSUE TITLE
Write a step-by-step aircraft design example

### ISSUE THREAD

**Issue by bqpd** [convexengineering/gplibrary#7]
(@whoburg): Educational example that steps through aircraft design models, building up from very simple to increasingly complex.

**Comment by 1ozturkbe** [comment]
Hmm, @bqpd does the SimPleAC qualify? I'm hoping to convert it to sizing/performance model based model incrementally as part of my thesis anyways.

**Comment by bqpd** [comment]
It totes will. I'll close this; it's covered in the new documentation plan.
