### ISSUE TITLE
Another signomial equality to profile

### ISSUE THREAD

**Issue by mayork** [convexengineering/gplibrary#87]
@1ozturkbe check out the SignomialEquality constraints on the altitude in lines 174 and 197 of `Commerical_Flight_Profile_Simple.py` at https://github.com/hoburg/gpkit-models/pull/73/commits/e6af55a0a2d8145bd2623c8c52197d2592fecddd
looks like there's some more interesting behavior with the linearization

**Comment by mayork** [comment]
also...the commented out signomial inequality constraints produce the exact same behavior so the problem is more fundamental with how the signomials are approximated

**Comment by 1ozturkbe** [comment]
It seems like this is a deprecated issue, since we deal with altitude changes a little differently now. Unless someone has an issue, closing.
